services:
  template-app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]